### ISSUE TITLE
When content ends and new playback is requested sender player is loosing control for remote player

### ISSUE THREAD

**Issue by radiantmediaplayer** [googlecast/CastVideos-chrome#1]
I am able to reproduce this issue with the sample Chrome sender app (v3) here on GitHub and our own implementation. Tested with Chrome Version 54.0.2840.99 m on Windows 10 and an up-to-date Chromecast device. 
To reproduce:
- install app from GitHub on local server and open index.html in Chrome (this also happens on a real site like http://www.staging-rmp.com/cast/)
- play first item (BBB) on sender device. Cast.
- wait or seek for content to end. 
- Cast device enters IDLE mode once content has finished
- Request a new play after content has ended and cast device is in IDLE mode
- LOADING of same media happens and player then go to PLAYING and then IDLE mode again. A this point sender device cannot control remote player anymore.
- Requesting a new play cause a new LOADING of media process which ends in correct and expected behaviour (e.g. sender can control remote). 

Can you please provide guidelines on how to properly handle end of content when the same media is reloaded?
Thanks
Arnaud

**Comment by neckaros** [comment]
I have the same issue. This is an issue with the SDK more than this demo.

With the default receiver:
if you switch media before the end you don't have any issue.
But if you wait untill play end and then change video the remotePlayer will note fire events nor be able to control the newly casted video.
But if during this video you switchagain before the end you are again able to control/receive events.
When having the issue casting an image and then a video also solve the issue.
it seems that when a video end you enter a problematic state

Where can we report this issue to Chrome cast sdk?

**Comment by radiantmediaplayer** [comment]
Hi @neckaros The google-cast-sdk issue tracker is at https://code.google.com/p/google-cast-sdk/issues/list. Can you open a bug over there?

**Comment by LeonNicholls** [comment]
Not a sample issue.

**Comment by neckaros** [comment]
Done and has been accepted.

For reference:
https://code.google.com/p/google-cast-sdk/issues/detail?id=1104&start=100
