### ISSUE TITLE
Unusable documentation, part 2

### ISSUE THREAD

**Issue by nicbou** [googlecast/CastVideos-chrome#14]
A few months ago, [I created a ticket](https://github.com/googlecast/CastVideos-chrome/issues/11) regarding the ChromeCast's lack of comprehensive examples and documentation. I recently resumed work on my project that worked with the ChromeCast, and I was a bit disappointed to see the documentation hasn't changed.

Based on [this much better example](https://gist.github.com/guerrerocarlos/3aca64069853d8d24a83b481246f23ca), I solved my problem. I turned the solution into [another simple example](https://gist.github.com/nicbou/09c2aa744352381329f3d90670e412b9).

I did not generously comment my gist as I would expect a demo to be commented, but it wasn't originally meant to be shared. Nonetheless, it's a good starting point for comprehensible docs.

The other points in my previous ticket still apply. The current demos won't run without pulling a repository and don't explain any of what they do. They are a barrier for anyone who's tempted to develop a ChromeCast application.

**Comment by LeonNicholls** [comment]
Our response to your original ticket still apply. All our sample apps are designed to be pulled as code for you to host. The documentation explains how to use the Cast SDK for Chrome: https://developers.google.com/cast/docs/chrome_sender_integrate

**Comment by nicbou** [comment]
The problem is not that it's not there, but that it does not adequately fulfil its role.

**Comment by Fenny** [comment]
@nicbou I feel you, this is the whole reason I created my own wrapper at some point. 
If you curious, here is the link: 
https://github.com/fenny/castjs with an [online demo](https://fenny.github.io/Castjs/demo/)

**Comment by nicbou** [comment]
Me too @Fenny! Here's the link: https://github.com/nicbou/homeserver/blob/master/frontend/src/js/components/ChromeCastService.js

Here's the ChromeCast button that uses it: https://github.com/nicbou/homeserver/blob/master/frontend/src/js/components/ChromeCastButton.component.js

I've used it on my home server for about a year to stream videos to my projector, and it works great. I don't use it to control the video though (I use my phone for that), so your solution is likely more complete.

**Comment by hydra3333** [comment]
> I've used it on my home server for about a year to stream videos 

nicbou, Great !
I'm trying to do the same thing however am running into issues :-
https://github.com/googlecast/CastVideos-chrome/issues/24
Given it works for you, what did you do right ? :)

**Comment by nicbou** [comment]
I still use the file linked above. However I had to get a proper SSL certificate.

**Comment by hydra3333** [comment]
OK.  My web server is inaccessible from the internet, and I do not have a domain.
May I enquire how you went about it and who you went with to purchase the cert ?

I reckon google may have lost the plot a bit (rich people running it), likely forcing people to pay for domains and certs when an option to not use it inside a home LAN would be easily done - I'm a retiree, so yet another recurrent expense is not something I can really afford :( 

_Edit 2020/01: found a way to use a self-signed cert - even though a home browser baulks at it a bit, it still works._

_My vanilla hack at https://github.com/hydra3333/Pi4CC has **minimal changes** to the CastVideos-chrome sample as at January 2020; the back-end runs on a Raspberry Pi 4 with Apache or on a  Windows PC with IIS, while the front-end runs in a user chrome browser on a tablet or PC and uses the HTML5 "details" element to show/hide lists of videos._

_Thank you google, for the sample, even though it is a tad difficult for novices to understand.  I hope that one day you may consider a "dummies" version with a very greatly simplified interface exposing only a very few functions._

**Comment by nicbou** [comment]
Over two years later, I'm still disappointed that this ticket was closed without consideration. I still struggle to answer simple questions like "how to I set the start time on the ChromeCast". The documentation has not changed at all, and it's still as incomplete as before.
