### ISSUE TITLE
Non-compliance with design checklist - multiple senders / reconnection?

### ISSUE THREAD

**Issue by muton** [googlecast/CastVideos-chrome#16]
Based on the docs (https://developers.google.com/cast/docs/design_checklist/sender#sender-control-resume) I would expect this sample to pick up where it left off after a network disconnect/reconnect but it doesn't.

I would also expect it to maintain state (show info for the vid currently playing on the chromecast) after a browser refresh, rather than start casting Big Buck Bunny from the beginning.

I'm unable to have two instances of this sender running on different computers connected to the receiver simultaneously, I think this should be possible.

(Have I misunderstood the checklist requirements?)

**Comment by jtromo** [comment]
This is correct, a new version of the sample will be released soon that will maintain the cast session state properly.

**Comment by jtromo** [comment]
Fixed
