### ISSUE TITLE
adding custom extension to chromecast's browser

### ISSUE THREAD

**Issue by surinder83singh** [googlecast/CastVideos-chrome#18]
want to add user-agent manager extension on chromecast device, plus there should be a way to add mouse/keyboard events using remove extension on desktop/android/ios so that we can use chromecast as a normal browser. dont want to go in wrong direction using https://forum.xda-developers.com/showthread.php?t=2382364 .

please tell me is it feasible without chromecast device hardware changes. or you don't want such features in chromecast

**Comment by LeonNicholls** [comment]
Extensions are not supported on cast devices; Cast devices are optimized for media playback and not web browsing.

**Comment by surinder83singh** [comment]
any way to add extension ?, can i get source code for chromecast ?
