### ISSUE TITLE
Question: multiple players handling

### ISSUE THREAD

**Issue by stefanovualto** [googlecast/CastVideos-chrome#19]
Does the google-cast button handle multiple players on the same page?

If yes how can I pass to it the element to cast?

**Comment by LeonNicholls** [comment]
It can, but you have to provide the right media information to the Cast SDK.

**Comment by stefanovualto** [comment]
Thank you, I think you gave me the right tips for another issue! 👍 

So that means that the click event by default only trigger a sessionRequest, am I right?

Is there an example somewhere or a schema of the lifeCycle that that explains what is needed in which order? I think it would be very helpful.

Have a great day, you saved me a lot of time! 🤗

**Comment by LeonNicholls** [comment]
Once you have a session, you just follow the same steps as with a single video. But you have to manage the metadata.
