### ISSUE TITLE
On iOS 10 Chrome 54 cast button does not show

### ISSUE THREAD

**Issue by radiantmediaplayer** [googlecast/CastVideos-chrome#2]
iOS 10.1.1
Chrome 54.0.2840.91
I tried the sample app provided here on GitHub which makes use of the `<button is="google-cast-button"></button>` on Chrome for iOS and the cast icon does not show. 
This issue can also be reproduced in our application. 
Tried on 2 different iOS 10 devices (iPhone + iPad) with same results.
The cast icon does show on Chrome 54 for Android 6/7.
Thanks
Arnaud

**Comment by LeonNicholls** [comment]
There is a known issue with Chrome on iOS that will be resolved in the future.
