### ISSUE TITLE
[Deprecation] Errors for M73 ( March 2019 ) 

### ISSUE THREAD

**Issue by Fenny** [googlecast/CastVideos-chrome#21]
![img](https://i.imgur.com/fbSQT4D.png)

```
cast_framework.js:60 [Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.
cast_framework.js:54 [Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.
```

**Comment by m-otoguro** [comment]
Schedule may be delayed, but warnings are still seen.

cast_framework.js:60
> [Deprecation] document.registerElement is deprecated and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.

cast_framework.js:54
> [Deprecation] Element.createShadowRoot is deprecated and will be removed in M80, around February 2020. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.

**Comment by m-otoguro** [comment]
I don't see errors any more.
Did it be fixed?

**Comment by Fenny** [comment]
Yup they fixed it :)
