### ISSUE TITLE
Is it working with Cordova?

### ISSUE THREAD

**Issue by desmeit** [googlecast/CastVideos-chrome#28]
Is it possible to integrate this Cast Chrome Sender SDK into a Cordova App? Or does it only work in a Chrome Browser?

**Comment by janimakinen** [comment]
To my experience this only works on a desktop, any dev here available to comment?

**Comment by jtromo** [comment]
We recommend using the Native SDKs for iOS and Android platforms. 

Chrome on iOS is not supported with Cast. Chrome on Android is supported, but we cannot guarantee it will work with Cordova.
