### ISSUE TITLE
On Chrome for Android casting cannot be disengaged with cast button

### ISSUE THREAD

**Issue by radiantmediaplayer** [googlecast/CastVideos-chrome#3]
Tested on 2 Chromecast devices (v1 and v2). 
Sender is Chrome 54.0.2840.85 on Android 7.0.0 or 6.0.1 (cast v3).
This issue can be reproduced from the sample Chrome app here on GitHub and in our custom app.
When cast button is interacted with casting works as expected.
While casting is engaged when the cast icon from the player is interacted with one would expect casting to disengage. 
Instead an overlay menu appears ("Cast to" and a waiting bar with "Finding devices"). This goes on forever and casting is never disengaged.
Casting can be disengaged using the top-down menu on Android (the one that shows when you swipe from the top of the device to the bottom). Using the stop button in this menu does work as expected.

Thanks
Arnaud

**Comment by LeonNicholls** [comment]
Please file a bug against Chrome.
