### ISSUE TITLE
Wish-list: Chromecast Audio example

### ISSUE THREAD

**Issue by macetw** [googlecast/CastVideos-chrome#36]
Is pushing an audio clip (a mp3) look any different in this framework? It would be nice to have a couple of examples that demonstrate this.

It's probably not that different, but it would be helpful to have an example.

Thank you for posting this!

**Comment by jtromo** [comment]
Using an audio clip could be the same process as a video, where you would use the audio clip URL for the contentId/contentUrl and set the contentType to the appropriate MIME type in the MediaInfo: https://developers.google.com/cast/docs/reference/web_sender/chrome.cast.media.MediaInfo

If you want to support Audio Only device, be sure to check "Supports casting to audio only devices" in your Cast Developer Console.  (https://developers.google.com/cast/docs/audio/)

We've added a TODO to provide an audio clip sample as well.
