### ISSUE TITLE
Cast button not showing up for Custom Receiver or Styled Media Receiver Applications

### ISSUE THREAD

**Issue by vivek8568** [googlecast/CastVideos-chrome#41]
Hi there,

I have cloned this repo and trying to cast the media from my browser, but Cast button is not visible (checked in elements & found "display: none" for it). Although it's working fine for **DEFAULT_MEDIA_RECEIVER**.

Steps I followed:
1. Registered my device on google cast console [status - Ready For Testing].
2. Registered Application and configured the "Application ID" into sender App (Tested for both Custom & Styled Media Receiver)
3. Deployed both Sender & Receiver applications and put the URL into cast console URLs.

Can anyone help me to know if something is missing or wrong in the above steps. 
**Note**: Working fine for DEFAULT_MEDIA_RECEIVER & I'm connected to the same network.

Thanks

**Comment by joeyparrish** [comment]
Is your registered receiver app in a "published" state in the developer console?

**Comment by vivek8568** [comment]
Hi, Sorry for late reply but I found the issue. I was using the wrong Serial Number to register my application. Actually there are multiple serial numbers like - 
1. In CC box
2. Settings -> About -> Status -> S/N
3. Setting -> Cast ->  S/N

Here is the link to find the correct S/N - https://developers.google.com/cast/docs/registration#find_device_serial_number
