### ISSUE TITLE
Not working on iOS Chrome

### ISSUE THREAD

**Issue by protyposis** [googlecast/CastVideos-chrome#5]
Hi!
Should this sample app be working in Chrome on iOS? 

As far as I understand the [docs](https://developers.google.com/cast/docs/chrome_sender_setup), there are no limitations documented regarding to iOS. Still, the `cast.framework.RemotePlayer` (and other classes in the `cast.framework` namespace) are undefined on latest Chrome (tested on iPhones and iPads running iOS 9 and iOS 10). Interestingly, `cast.framework.CastContext` is available and a session can be requested.

**Comment by LeonNicholls** [comment]
Are you using the __onGCastApiAvailable callback?

**Comment by protyposis** [comment]
Yes, using this example unmodified from the master branch. Even within this callback, `RemotePlayer` is undefined.

**Comment by protyposis** [comment]
Some additional information on this issue. In lack of a debug bridge on iOS, I changed the `__onGCastApiAvailable` callback to output the members of the `cast.framework` namespace like this:

```js
window['__onGCastApiAvailable'] = function(isAvailable) {
  if (isAvailable) {
    for (var member in cast.framework) {
      document.getElementById('carousel').innerHTML += '<br>' + member;
    }
    castPlayer.initializeCastPlayer();
  }
};
```

Here's the results:

Android 7.1.1 / Chrome 55.0.2883.91
Windows 10 / Chrome 55.0.2883.87
```
VERSION
LoggerLevel
CastState
SessionState
CastContextEventType
SessionEventType
RemotePlayerEventType
ActiveInputState
setLoggerLevel
EventData
ApplicationMetadata
ApplicationStatusEventData
ApplicationMetadataEventData
ActiveInputStateEventData
MediaSessionEventData
VolumeEventData
CastSession
CastStateEventData
SessionStateEventData
CastOptions
CastContext
RemotePlayer
RemotePlayerChangedEvent
RemotePlayerController
```

iPhone 6 / iOS 9.3.4 / Chrome 55.0.2883.79
iPhone 7 / iOS 10.2 / Chrome 55.0.2883.79
iPad Air 2 / iOS 10.0.2 / Chrome 54.0.2840.66
```
VERSION
LoggerLevel
CastState
SessionState
CastContextEventType
SessionEventType
RemotePlayerEventType
ActiveInputState
setLoggerLevel
EventData
ApplicationMetadata
ApplicationStatusEventData
ApplicationMetadataEventData
ActiveInputStateEventData
MediaSessionEventData
VolumeEventData
CastSession
CastStateEventData
SessionStateEventData
CastOptions
CastContext
```

`RemotePlayer`, `RemotePlayerChangedEvent`, and `RemotePlayerController` are missing on iOS.

All of the above have `isAvailable` set to `true`. The exception is another iPad Air 2 / iOS 10.2 / Chrome 55.0.2883.79, where `isAvailable` is `false` for unknown reasons.

**Comment by LeonNicholls** [comment]
Thanks. We are investigating.

**Comment by ibz096** [comment]
I noticed that the "button is="google-cast-button"" does not work on Chrome for iOS.

**Comment by iaco79** [comment]
Button is="google-cast-button"  also doesn't work on windows Chrome "56.0.2924.87", so the user will always need to push the cast button next to the address bar I assume?

**Comment by ibz096** [comment]
The "google-cast-button" works fine on  Chrome "56.0.2924.87. From what i experienced the button does not appear unless a chromecast device is on and discovered. But from what you are saying the button does not work at all.

**Comment by radiantmediaplayer** [comment]
https://github.com/googlecast/CastVideos-chrome/issues/2

**Comment by kslimani** [comment]
Does someone has a clue how YouTube is technically able to do that ? (_on m.youtube.com they display cast icon on top menu bar_) It seems they found a workaround for Chrome on iOS device.

**Comment by kslimani** [comment]
After doing more tests, it _seems_ that ~~`window['__onGCastApiAvailable']` is broken on Chrome iOS~~.

Results of my tests is with Chrome browser on some iOS devices, the `window.chrome` property may not be immediately available.

A workaround is to use a simple `setTimeout` loop to wait for `window.chrome` to be available. Then simply check for `window.chrome.cast` etc...

_EDIT: added more explanations._

**Comment by protyposis** [comment]
Gave it another try today and it's now working on all my iOS 10 devices :) Just listening to `__onGCastApiAvailable`, no timeout workaround. Still not working on iOS 9.

**Comment by kslimani** [comment]
@protyposis i don't think that listening only on `__onGCastApiAvailable` is enough. In the meantime that Google fix the bug, i recommand to use the workaround i described (_for me it work on any iOS device with Chome browser with Cast support_).

Take a look at this [piece of code](https://github.com/clappr/clappr-chromecast-plugin/commit/8e3362edc5e2e166dcd80ac2ef1749fe403cf645).

**Comment by protyposis** [comment]
I can only speak from my own experience because I just ran the tests, and that is that listening for `__onGCastApiAvailable` *is* enough. 

Yes, `window.chrome` is not immediately available, but that's what the callback is for. It gets called once it becomes available. The original issue was that only part of the `cast.framework` namespace was available when the callback was called; that is now fixed on iOS 10, but not on iOS 9. On iOS 9, the `RemotePlayer` is still missing, no matter how long I wait and how often I try.

**Comment by kslimani** [comment]
@protyposis : on my iPad with iOS 9.3.5 (13G36) it is working with my workaround.

**Comment by kslimani** [comment]
@protyposis could you please try the following :

Clone [this exemple](https://github.com/googlecast/CastHelloVideo-chrome/) and edit the `index.html` file to add this button (for example, before the "Lauch app" button) :

```html
<button onclick="initializeCastApi()">Init API</button>
```

Then serve the page using a local http server and try init the api by click on button, then launch app, load media and play. 

Tell me if it is working with your iOS 9 device ?

**Comment by protyposis** [comment]
Yes it is working, but only because it is *not* using `cast.framework`.

**Comment by kslimani** [comment]
@protyposis you are correct. I did not make tests with `cast.framework`. The workaround seems to fix only if using low level api.

**Comment by perlambaek** [comment]
This is still not working for me at all, has anyone actually gotten this to work?

**Comment by jpellizzari** [comment]
Seems like this is possibly related: https://stackoverflow.com/questions/26483541/referenceerror-cant-find-variable-gcrweb

**Comment by LeonNicholls** [comment]
Ensure that you load CAF before instantiating any custom components.

**Comment by stkrzysiak** [comment]
This is still an issue, I immediately see `Uncaught ReferenceError: cast is not defined` a bit frustrating.
Edit: This issue happens when you open index.html w/ chrome. Throw a web server in front of it and access it that way and everything works fine.

**Comment by lbcd** [comment]
Hello it doesn't work for me. ChromeCast button just not appear. 
Chrome version : 69.0.3497.91
Work fine on a PC but not on a iPad with Chrome for both.

**Comment by lbcd** [comment]
Update this message on the next day it doesn't work anymore....
---
In fact you can cast if you change in index.html that
```
            <script type="text/javascript">
                var castPlayer = new CastPlayer();
                //window['__onGCastApiAvailable'] = function(isAvailable) {
                //    if (isAvailable) {
                        setTimeout(
                            function () { castPlayer.initializeCastPlayer();},
                            1000
                        ) ;
                //    }
                //};
            </script>
```

But button is not displayed just a black placeholder. And especially you can control anything by play / pause... 
And of course it's an ugly way to have it working.

**Comment by lbcd** [comment]
I going to become crazy with this bug. It seems that chrome 69 have a bug about that. I tried to implement CAF directly : https://developers.google.com/cast/docs/chrome_sender_integrate it works on Chrome computer but not on Chrome iOS.

I have logged `cast.framework.CastContext.getInstance().getCastState()` it is NOT_CONNECTED or CONNECTED when playing on the chromecast on a computer.
It stays to NO_DEVICE_AVAILABLE on Chrome on iOS.

I tried to go on website with ChromeCast on their player but none of then diplay ChromeCast button.

Hope Google will fix this issue quickly.

**Comment by lbcd** [comment]
Incredible => https://bugs.chromium.org/p/chromium/issues/detail?id=872050&q=ios%20chromecast&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by radiantmediaplayer** [comment]
@lbcd well at least now we know we should not be expecting Google Cast support in Chrome for iOS.

**Comment by jtromo** [comment]
Closing issue since Chrome for iOS support is deprecated.
