### ISSUE TITLE
How to use `editTracksInfo` method

### ISSUE THREAD

**Issue by rafa8626** [googlecast/CastVideos-chrome#9]
I'm trying to use the `CastVideos.js` file here and adapt it to also display tracks; however, I haven't been able to achieve it. I don't want to activate them when loading, so how do I use the `editTracksInfo` in that current example? Or what element holds that method: remotePlayer or remotePlayerController, and where?

Any hints will be appreciated. Thanks in advance.

**Comment by LeonNicholls** [comment]
https://developers.google.com/cast/docs/reference/chrome/chrome.cast.media.Media#editTracksInfo

**Comment by rafa8626** [comment]
But if I call `chrome.cast.media.Media.editTracksInfo` gives me an error. That's why I was asking if there's something else I need to do, or where do I obtain the elements for the Media constructor and create an instance of it

**Comment by rafa8626** [comment]
Or is there a way from the remotePlayer or remotePlayerController to access that class instance?

**Comment by LeonNicholls** [comment]
Since this isn't an issue with this sample app, please file an issue with the Google Cast SDK tracker: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc

**Comment by plutotv-aaa** [comment]
> But if I call `chrome.cast.media.Media.editTracksInfo` gives me an error. That's why I was asking if there's something else I need to do, or where do I obtain the elements for the Media constructor and create an instance of it

@rafa8626 We're you able to find a good example on how this works?

**Comment by shubaz** [comment]
> > But if I call `chrome.cast.media.Media.editTracksInfo` gives me an error. That's why I was asking if there's something else I need to do, or where do I obtain the elements for the Media constructor and create an instance of it
> 
> @rafa8626 We're you able to find a good example on how this works?

const castSession = cast.framework.CastContext.getInstance().getCurrentSession();
const media = castSession.getMediaSession();
media.editTracksInfo(tracksInfoRequest, success, fail);
